# Generated by Django 3.2a1 on 2021-01-27 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('illrequest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='openurlrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('request', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='illrequest.illrequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='openurlrequest',
            index=models.Index(fields=['request', 'key'], name='illrequest__request_238b3f_idx'),
        ),
    ]
