# Generated by Django 3.2a1 on 2021-03-01 21:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('illrequest', '0002_auto_20210127_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='illrequestbase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='openurlrequest',
            name='request',
            field=models.ForeignKey(blank=True, db_index=False, on_delete=django.db.models.deletion.CASCADE, to='illrequest.illrequestbase'),
        ),
    ]
