# Generated by Django 3.2a1 on 2021-03-03 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('illrequest', '0003_auto_20210301_2159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='illrequest',
        ),
    ]
