# Generated by Django 3.2a1 on 2021-03-10 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('illrequest', '0004_delete_illrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='illmanualrequester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=255)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illrequest.illrequestbase')),
            ],
        ),
    ]
