# Generated by Django 3.2.4 on 2021-09-24 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('illrequest', '0006_relaisrequestsmade'),
    ]

    operations = [
        migrations.CreateModel(
            name='illrequestdiscoveredipaddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_ip', models.CharField(max_length=60)),
                ('outside_ip', models.CharField(max_length=60)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illrequest.illrequestbase')),
            ],
        ),
    ]
