# Generated by Django 3.2.4 on 2021-09-24 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('illrequest', '0007_illrequestdiscoveredipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='illrequestdiscoveredipaddress',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
